### ISSUE TITLE
ofxPd pdexample doesn't build in ofx 0.8.4

### ISSUE THREAD

**Issue by batchku** [danomatika/ofxPd#44]
trying to get the first example working with 0.8.4,
i've added the "additional c flags" and also confirmed that the header search paths include 

../../../addons/ofxPd/libs/libpd/pure-data/src

i'm getting compile errors:
/Users/ali/GoogleDrive/Development/of_v0.8.4_osx_release/apps/myApps/ofxPdTest01/src/ofApp.cpp:429:47: No member named 'numMessages' in 'ofxPd'

![image](https://cloud.githubusercontent.com/assets/518356/6943036/6c0266fe-d859-11e4-8683-e365f4842f6c.png)

**Comment by danomatika** [comment]
This is my fault. I removed the manually message polling interface from the libpd C++ wrapper but forgot to update ofxPd to reflect this. Just remove everything in the processEvents() function for now so your project will build. I'll update the ofxPd sources shortly.

**Comment by danomatika** [comment]
Ok, all fixed. Update ofxPd and regenerate your project.
