### ISSUE TITLE
Bug, duplicate symbols

### ISSUE THREAD

**Issue by Wah0airo** [danomatika/ofxPd#52]
I tried to include ofxPD in a Project but I became a linker error, 30 duplicate symbols. I tried to compile the examples, but was the same, again 30 duplicate symbols. 
I found some similar posts, but I couldn't find any solutions. I looks like there is a problem with "g_list_all.h" . I follow the instructions from Readme file. The errors are lister below.
I'm working with OF 0.98 on OSX Sierra, Xcode 8.3, ofxPd was compiled with the following flags:  -DHAVE_UNISTD_H -DUSEAPI_DUMMY -DPD -DLIBPD_EXTRA -DLIBPD_USE_STD_MUTEX -DHAVE_LIBDL
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_array.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_bang.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_canvas.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_clone.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_editor.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_graph.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_guiconnect.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_hdial.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_hslider.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_io.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_mycanvas.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_numbox.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_readwrite.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_rtext.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_scalar.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_template.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_text.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_toggle.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_traversal.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_vdial.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_vslider.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
g_vumeter.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
m_binbuf.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
m_pd.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
s_inter.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
s_loader.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
x_array.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
x_misc.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
x_scalar.o
duplicate symbol glistreloadingabstraction in:
g_all_guis.o
x_text.o
ld: 30 duplicate symbols for architecture x86_64

**Comment by danomatika** [comment]
Did you use the ProjectGenerator?

**Comment by Wah0airo** [comment]
Yes, I used the Project Generator. I create a new example too with the PG only with an example of  ofxPD,, the "duplicate symbols" still appears. The rest of Open Frameworks addons are working OK.

**Comment by danomatika** [comment]
I'm not seeing this issue with a fresh clone of ofxPd into a fresh download of OF 0.9.8. Both pdExample and an empty project using ofxPd build fine. I'm running macOS 10.12.4 and using Xcode 8.3.1.

**Comment by danomatika** [comment]
Ok cool. In general, it's best not to update the project the PG generates.

**Comment by danomatika** [comment]
As a followup, can you set the following in an *updated* project to see if it builds?

* Click on the project in the right-hand project tree
* Select the debug build target in the TARGETS list
* Click on the "Build Settings" tab
* Search for "No Common Blocks"
* Change the setting from "Yes" to "No"

**Comment by Wah0airo** [comment]
I changed the setting from "No common Blocks" in an updated project from "Yes" to "No", it builds.
Regards.

**Comment by danomatika** [comment]
"No common blocks" is now set via the "-fcommon" compiler flag in addon_config.mk.
